### ISSUE TITLE
rename admin-events to monitor-events

### ISSUE THREAD

**Issue by haseebrabbani** [arbitraryexecution/forta-bot-templates#29]
the name of the admin-events template may imply that its only meant for admin-related events, but it is actually a more generic event monitoring bot. I think it should be renamed to be clearer and consistent with the monitor-functions template i.e. monitor-events

**Comment by echoAE** [comment]
Addressed by pull request: https://github.com/arbitraryexecution/forta-bot-templates/pull/33
